(()=>{
const SAVE='master-investigation-v1', C=window.MASTER_CASE, S=window.MASTER_SOURCES;
const $=q=>document.querySelector(q); let ctx=null, muted=false, queue=[], selected=[], interviewStatement=null;
const fresh=()=>({sceneId:'cold',discoveredEvidence:[],inspected:[],conclusions:{},interviewFlags:{},characterKnowledge:{investigadora:[]},leadOrder:[],completedBeats:[],recontextualizedEvidence:[],hintLevels:{},sourceViews:[],finished:false});
let state=fresh();
function save(){localStorage.setItem(SAVE,JSON.stringify(state));syncContinue()}
function load(){try{return {...fresh(),...JSON.parse(localStorage.getItem(SAVE))}}catch{return fresh()}}
function scene(){return C.scenes.find(s=>s.id===state.sceneId)}
function unlockAudio(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)(); if(ctx.state==='suspended')ctx.resume(); tone(520,.06,.025);setTimeout(()=>tone(690,.08,.02),70)}
function tone(freq,dur=.06,vol=.025){if(muted||!ctx||ctx.state!=='running')return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(vol,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+dur);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+dur)}
function immersive(){document.documentElement.requestFullscreen?.().catch(()=>{});screen.orientation?.lock?.('landscape').catch(()=>{})}
function syncContinue(){$('#continue').hidden=!localStorage.getItem(SAVE)}
function showGame(){unlockAudio();immersive();$('#start').classList.remove('active');$('#game').classList.add('active');renderScene()}
function start(){state=fresh();save();showGame()}
function renderScene(replayIntro=true){const s=scene();selected=[];interviewStatement=null;$('#chapter').textContent=s.chapter;$('#scene-title').textContent=s.title;$('#date-card').textContent=s.date;$('#background').src=s.bg;$('#background').alt=s.title;$('#evidence-count').textContent=state.discoveredEvidence.length;$('#interview').hidden=!(s.interview&&state.conclusions[s.id]);$('#hotspots').innerHTML='';s.hotspots.forEach(([id,label,x,y])=>{const b=document.createElement('button');b.className='hotspot '+(state.inspected.includes(`${s.id}:${id}`)?'seen':'');b.style.left=x+'%';b.style.top=y+'%';b.dataset.evidence=id;b.setAttribute('aria-label',label);b.textContent=state.inspected.includes(`${s.id}:${id}`)?'✓':'+';$('#hotspots').append(b)});closePanel();if(replayIntro)playDialogue(s.intro);save()}
function playDialogue(lines){if(!lines?.length){$('#dialogue').classList.add('hidden');return}queue=[...lines];$('#dialogue').classList.remove('hidden');nextLine()}
function nextLine(){const row=queue.shift();if(!row){$('#dialogue').classList.add('hidden');return}$('#speaker').textContent=row[0];$('#line').textContent=row[1];tone(210+row[1].length%90,.035,.012)}
function inspect(id){const s=scene(),key=`${s.id}:${id}`,ev=C.evidence[id];if(!state.inspected.includes(key))state.inspected.push(key);if(!state.discoveredEvidence.includes(id)){state.discoveredEvidence.push(id);state.characterKnowledge.investigadora.push(id);notice(`EVIDÊNCIA ADICIONADA · ${ev.title}`);tone(780,.11,.035)}else notice('Há algo neste item que talvez mereça nova leitura.');renderScene(false);openEvidence(id);save()}
function notice(text){const n=$('#notice');n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1800)}
function openPanel(kicker,title,html){$('#panel-kicker').textContent=kicker;$('#panel-title').textContent=title;$('#panel-body').innerHTML=html;$('#panel').classList.remove('hidden')}
function closePanel(){$('#panel').classList.add('hidden')}
function tag(status){return `<span class="tag">${status}</span>`}
function openEvidence(id){const e=C.evidence[id],src=S[e.sourceId];openPanel(e.type,e.title,`${tag(e.status)}<p>${e.summary}</p><p class="dossier-meta">Fato: ${e.eventDate||'—'} · documento: ${e.documentDate||'—'} · conhecido pela PF: ${e.knownToPFDate||'—'} · publicado: ${e.publishedDate||'—'}</p>${src?`<p><a class="source-link" target="_blank" rel="noopener" href="${src.url}">Fonte: ${src.publisher}</a></p>`:''}`)}
function openHypothesis(){const s=scene();const available=state.discoveredEvidence.filter(id=>s.hotspots.some(h=>h[0]===id)||['loteB'].includes(id));let html=`<p class="question">${s.question}</p><h3>1. Separe os registros relevantes</h3><div class="evidence-list">${available.map(id=>{const e=C.evidence[id];return `<button class="evidence-card" data-ev="${id}">${tag(e.status)}<strong>${e.title}</strong><small>${e.summary}</small></button>`}).join('')}</div><h3>2. Formule a conclusão</h3><div class="hypothesis-list">${s.answers.map(a=>`<button class="hypothesis" data-answer="${a[0]}">${a[1]}</button>`).join('')}</div><div id="hyp-result"></div>`;openPanel('INFERÊNCIA',s.title,html);selected=[];document.querySelectorAll('[data-ev]').forEach(b=>b.onclick=()=>{const id=b.dataset.ev;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<3)selected.push(id);b.classList.toggle('selected')});document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>submitHypothesis(b.dataset.answer))}
function submitHypothesis(answer){const s=scene();const evidenceOK=s.sets.some(set=>set.every(id=>selected.includes(id)));const answerOK=answer===s.accepted;const box=$('#hyp-result');if(answerOK&&evidenceOK){state.conclusions[s.id]='SUPPORTED';state.completedBeats.push(s.id);box.className='result';box.innerHTML=`<strong>SUPPORTED</strong><p>${s.outcome}</p><button id="advance" class="submit">Prosseguir</button>`;tone(870,.18,.04);$('#advance').onclick=()=>advance()}else{state.conclusions[s.id]=answerOK?'INCOMPLETE':'CONTRADICTED';box.className='result warn';box.innerHTML=`<strong>${answerOK?'INCOMPLETE':'CONTRADICTED'}</strong><p>${answerOK?'A conclusão é precisa, mas os registros selecionados ainda não a sustentam.':'A formulação vai além do que os registros demonstram. A linha continua aberta.'}</p>`;tone(150,.12,.025)}save()}
function advance(){const s=scene();if(s.interview){closePanel();$('#interview').hidden=false;openInterview();return}if(s.branch){openBranch();return}if(s.end){finish();return}go(s.next)}
function go(id){state.sceneId=id;renderScene()}
function openInterview(){let html=`<p class="question">Qual afirmação deve ser pressionada com documento?</p><div class="statement-list">${C.interview.statements.map(x=>`<button class="statement" data-st="${x.id}"><strong>${x.text}</strong><small>${x.detail}</small></button>`).join('')}</div><div id="interview-step"></div>`;openPanel('OITIVA · DRAMATIZAÇÃO', 'Origem da carteira',html);document.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>{interviewStatement=b.dataset.st;document.querySelectorAll('[data-st]').forEach(x=>x.classList.toggle('selected',x===b));showInterviewEvidence()})}
function showInterviewEvidence(){const ids=state.discoveredEvidence.filter(id=>C.interview.acceptedEvidence.includes(id));$('#interview-step').innerHTML=`<p>Apresente um registro. Uma escolha imprecisa não encerra a oitiva.</p><div class="evidence-list">${ids.map(id=>`<button class="evidence-card" data-present="${id}">${C.evidence[id].title}</button>`).join('')}</div><div id="interview-result"></div>`;document.querySelectorAll('[data-present]').forEach(b=>b.onclick=()=>presentEvidence(b.dataset.present))}
function presentEvidence(id){const ok=interviewStatement===C.interview.correctStatement&&C.interview.acceptedEvidence.includes(id),box=$('#interview-result');if(ok){state.interviewFlags.fantasma='completed';box.className='result';box.innerHTML=`<strong>CONFRONTO SUSTENTADO</strong><p>${C.interview.success}</p><button id="leave-interview" class="submit">Encerrar oitiva</button>`;$('#leave-interview').onclick=()=>go('retorno');tone(870,.15,.04)}else{state.interviewFlags.fantasma='fail-forward';box.className='result warn';box.innerHTML='<strong>A resposta resiste.</strong><p>“O que esse documento prova sobre esta frase, exatamente?” A pergunta expõe uma informação lateral, mas essa linha perde precisão. Você pode pressionar outra afirmação.</p>';tone(150,.1,.025)}save()}
function openBranch(){openPanel('DUAS PORTAS','Qual linha abrir primeiro?',`<p>As duas linhas serão investigadas. A ordem muda o contexto de entrada.</p><div class="choice-door"><button data-lead="turma">A TURMA<small>rastros presenciais, mensagens e pagamentos alegados</small></button><button data-lead="meninos">OS MENINOS<small>proveniência digital e limite da inferência</small></button></div>`);document.querySelectorAll('[data-lead]').forEach(b=>b.onclick=()=>{state.leadOrder=[b.dataset.lead];go(b.dataset.lead)})}
function afterLead(){const s=scene();if(!state.leadOrder.includes(s.lead))state.leadOrder.push(s.lead);if(state.leadOrder.length===1){const next=s.lead==='turma'?'meninos':'turma';state.sceneId=next;renderScene();playDialogue(next==='turma'?[['INVESTIGADORA','A linha digital devolveu um nome. Agora quero ver onde ele aparece fora da tela.']]:[['INVESTIGADORA','O registro presencial trouxe o mesmo nó. Quero saber o que a evidência digital realmente sustenta.']])}else go('final')}
const originalAdvance=advance;advance=function(){const s=scene();if(s.lead){closePanel();afterLead();return}originalAdvance()};
function openDossier(){const rows=state.discoveredEvidence.map(id=>{const e=C.evidence[id],src=S[e.sourceId];return `<article class="dossier-item"><div>${tag(e.status)} ${tag(e.type)}</div><h3>${e.title}</h3><p>${e.summary}</p><p class="dossier-meta">Evento ${e.eventDate||'—'} · documento ${e.documentDate||'—'} · disponível à investigação ${e.knownToPFDate||'—'}</p>${src?`<a class="source-link" href="${src.url}" target="_blank" rel="noopener">${src.publisher}</a>`:''}</article>`}).join('')||'<p>Nenhum item encontrado.</p>';openPanel('DOSSIÊ','Evidências encontradas',rows)}
function hint(){const s=scene(),n=(state.hintLevels[s.id]||0)+1;state.hintLevels[s.id]=Math.min(3,n);const texts=[`Releia a pergunta sem tentar resolver o caso inteiro: ${s.question}`,`Procure dois registros que falem do mesmo objeto, mas não necessariamente da mesma forma.`,`Inspecione ${s.hotspots.find(h=>!state.inspected.includes(`${s.id}:${h[0]}`))?.[1]||'os itens da cena novamente'} e compare datas, origem e limite do que cada item prova.`];openPanel(`DICA ${Math.min(n,3)}`,'Uma direção, não a resposta',`<p>${texts[Math.min(n,3)-1]}</p>`);save()}
function finish(){state.finished=true;save();openPanel('ESTADO · PENDENTE','O relatório vira o caso',`<div class="end-image"></div><p>A cópia permanece sem destino definido na interface. Nenhuma conclusão de culpa é produzida.</p><p class="dossier-meta">15/09: pedido de vista, sem mérito julgado. 19/09: auxílio técnico solicitado à PF para a cópia.</p><button id="restart" class="submit">Reiniciar investigação</button>`);$('#restart').onclick=start}
function about(){openPanel('TRANSPARÊNCIA','Fatos, alegações e dramatização',`<p>A investigadora, a coordenadora, a perita e a analista são personagens ficcionais compostas. Conversas privadas são dramatização.</p><p>Decisões, registros e datas sensíveis usam etiquetas epistemológicas e fontes no Dossiê. Relatório policial não é sentença; versão da defesa não é fato estabelecido.</p><p>A oitiva dramatizada usa apenas padrões conversacionais observáveis nas oitivas públicas de 30/12/2025 e 28/08/2026, sem copiar fraseologia distintiva.</p>`)}
$('#new').onclick=start;$('#continue').onclick=()=>{state=load();showGame()};$('#about').onclick=about;$('#close-panel').onclick=closePanel;$('#dialogue').onclick=nextLine;$('#infer').onclick=openHypothesis;$('#dossier').onclick=openDossier;$('#hint').onclick=hint;$('#interview').onclick=openInterview;$('#audio').onclick=()=>{muted=!muted;$('#audio').textContent=muted?'×':'♪';if(!muted)unlockAudio()};$('#bonus').onclick=()=>openPanel('EXTRA PRESERVADO','Punhal Verde e Amarelo',`<div class="bonus-note"><p>O bônus existente foi preservado nos assets e no histórico canônico. Ele está fora do fluxo principal desta campanha investigativa enquanto passa por adaptação ao novo motor.</p></div>`);
$('#hotspots').addEventListener('click',event=>{const button=event.target.closest('[data-evidence]');if(button){event.stopPropagation();inspect(button.dataset.evidence)}});
window.__MASTER_TEST__={fresh,getState:()=>state,setState:x=>state=x,renderScene,submitHypothesis,go,load,save,scenes:C.scenes,evidence:C.evidence};syncContinue();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
