window.MASTER_CASE={
 characters:{
  mara:{name:'MARA',role:'Investigadora',voice:146},lia:{name:'LIA',role:'Coordenadora',voice:130},
  bia:{name:'BIA',role:'Analista financeira',voice:164},jo:{name:'JO',role:'Perita digital',voice:174},
  defesa:{name:'DEFESA',role:'Manifestação pública',voice:138},depoente:{name:'DEPOENTE',role:'Oitiva dramatizada',voice:124}
 },
 evidence:{
  mandado:{title:'Ordem em execução',type:'MEDIDA JUDICIAL',summary:'A equipe tinha ordem válida para efetuar a primeira prisão em Guarulhos.',eventDate:'17/11/2025',documentDate:'17/11/2025',knownToPFDate:'17/11/2025',knownToPlayerDate:'17/11/2025',publishedDate:'18/11/2025',status:'DOCUMENTADO',sourceId:'prisao1',knownBy:['mara','lia']},
  voo:{title:'Cartão de embarque',type:'REGISTRO',summary:'Dubai, portão 312, embarque naquela noite. O registro não contém a finalidade da viagem.',eventDate:'17/11/2025',documentDate:'17/11/2025',knownToPFDate:'17/11/2025',knownToPlayerDate:'17/11/2025',publishedDate:'18/11/2025',status:'DOCUMENTADO',sourceId:'prisao1',knownBy:['mara','lia']},
  defesa:{title:'Versão apresentada pela defesa',type:'MANIFESTAÇÃO',summary:'A defesa relacionou a viagem a negociação comercial. Essa versão só entrou no registro depois da prisão.',eventDate:'17/11/2025',documentDate:'25/11/2025',knownToPFDate:'25/11/2025',knownToPlayerDate:'25/11/2025',publishedDate:'25/11/2025',status:'CONTESTADO',sourceId:'defesa_viagem',knownBy:['mara','lia']},
  planilha:{title:'Relação de cessão — recorte composto',type:'REGISTRO FINANCEIRO',summary:'Recorte dramatizado: uma relação atribui determinada origem e data a uma carteira. Identificador, valores e datas foram compostos para o puzzle.',eventDate:'2024',documentDate:'2024',knownToPFDate:'2024',knownToPlayerDate:'2024',publishedDate:'',status:'DRAMATIZAÇÃO',sourceId:'bc_comunicacao',knownBy:['mara','bia','lia']},
  origem:{title:'Arquivo de formação — recorte composto',type:'REGISTRO FINANCEIRO',summary:'Recorte dramatizado: o mesmo identificador aparece com origem e cronologia diferentes. Identificador, valores e datas foram compostos.',eventDate:'2024',documentDate:'2024',knownToPFDate:'2024',knownToPlayerDate:'2024',publishedDate:'',status:'DRAMATIZAÇÃO',sourceId:'bc_comunicacao',knownBy:['mara','bia','lia']},
  oficioBC:{title:'Comunicação do Banco Central',type:'OFÍCIO',summary:'A apuração não nasceu de uma intuição individual: inconsistências nas cessões Master/BRB foram comunicadas institucionalmente.',eventDate:'2024',documentDate:'22/07/2024',knownToPFDate:'22/07/2024',knownToPlayerDate:'22/07/2024',publishedDate:'',status:'DOCUMENTADO',sourceId:'bc_comunicacao',knownBy:['mara','bia','lia']},
  tirreno:{title:'Instrumento de origem declarada',type:'CONTRATO',summary:'Documento apresentado para situar a Tirreno na origem da carteira examinada.',eventDate:'2024–2025',documentDate:'2025',knownToPFDate:'2025',knownToPlayerDate:'30/12/2025',publishedDate:'2026',status:'ALEGADO',sourceId:'oitiva1',knownBy:['mara','bia','lia','depoente']},
  brb:{title:'Cessão registrada ao BRB',type:'CESSÃO',summary:'O registro identifica carteira, data e cessão; a cadeia documental da origem continuou controvertida.',eventDate:'2025',documentDate:'2025',knownToPFDate:'2025',knownToPlayerDate:'30/12/2025',publishedDate:'2026',status:'DOCUMENTADO',sourceId:'oitiva1',knownBy:['mara','bia','lia','depoente']},
  fala:{title:'Resposta sobre a origem',type:'DEPOIMENTO',summary:'O depoente contesta a premissa, distingue decisão macro de execução e não fixa de memória a sequência documental.',eventDate:'30/12/2025',documentDate:'30/12/2025',knownToPFDate:'30/12/2025',knownToPlayerDate:'30/12/2025',publishedDate:'29/01/2026',status:'CONTESTADO',sourceId:'oitiva1',knownBy:['mara','lia','depoente']},
  liquidacao:{title:'Ato de liquidação',type:'ATO DO BANCO CENTRAL',summary:'O Banco Central decretou a liquidação extrajudicial em 18 de novembro. É um fato posterior e distinto da prisão.',eventDate:'18/11/2025',documentDate:'18/11/2025',knownToPFDate:'18/11/2025',knownToPlayerDate:'18/11/2025',publishedDate:'18/11/2025',status:'DOCUMENTADO',sourceId:'liquidacao',knownBy:['mara','lia','bia']},
  notaSTF:{title:'Nota dos dez ministros',type:'NOTA INSTITUCIONAL',summary:'Manteve atos anteriores, registrou atendimento a pedidos da PF e PGR e informou livre redistribuição a pedido do relator.',eventDate:'12/02/2026',documentDate:'12/02/2026',knownToPFDate:'12/02/2026',knownToPlayerDate:'12/02/2026',publishedDate:'12/02/2026',status:'DOCUMENTADO',sourceId:'stf_nota',knownBy:['mara','lia','jo']},
  redistribuicao:{title:'Redistribuição da relatoria',type:'REGISTRO PROCESSUAL',summary:'Os feitos foram redistribuídos e André Mendonça assumiu a relatoria.',eventDate:'12/02/2026',documentDate:'12/02/2026',knownToPFDate:'12/02/2026',knownToPlayerDate:'12/02/2026',publishedDate:'12/02/2026',status:'DOCUMENTADO',sourceId:'stf_nota',knownBy:['mara','lia','jo']},
  fluxo:{title:'Despacho de 19 de fevereiro',type:'DECISÃO',summary:'Autorizou fluxo ordinário para perícias em cerca de cem dispositivos e diligências que não exigiam autorização judicial.',eventDate:'19/02/2026',documentDate:'19/02/2026',knownToPFDate:'19/02/2026',knownToPlayerDate:'19/02/2026',publishedDate:'19/02/2026',status:'DOCUMENTADO',sourceId:'mendonca_fluxo',knownBy:['mara','lia','jo']},
  financeiro:{title:'Carteiras e cessões',type:'PEÇA DE ANÁLISE',summary:'Registros financeiros permanecem no primeiro núcleo descrito pela investigação.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',knownToPlayerDate:'04/03/2026',publishedDate:'04/03/2026',status:'ALEGADO',sourceId:'quatro_nucleos',knownBy:['mara','lia','bia','jo']},
  institucional:{title:'Contato com agente público',type:'PEÇA DE ANÁLISE',summary:'Um conjunto de registros foi associado pela PF ao núcleo de corrupção institucional.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',knownToPlayerDate:'04/03/2026',publishedDate:'04/03/2026',status:'ALEGADO',sourceId:'quatro_nucleos',knownBy:['mara','lia','bia','jo']},
  ocultacao:{title:'Cadeia patrimonial',type:'PEÇA DE ANÁLISE',summary:'Ativos e transferências foram associados pela PF ao núcleo de ocultação patrimonial e lavagem.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',knownToPlayerDate:'04/03/2026',publishedDate:'04/03/2026',status:'ALEGADO',sourceId:'quatro_nucleos',knownBy:['mara','lia','bia','jo']},
  intimidacao:{title:'Monitoramento e pressão',type:'PEÇA DE ANÁLISE',summary:'Mensagens e registros foram associados pela PF a intimidação e obstrução.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',knownToPlayerDate:'04/03/2026',publishedDate:'04/03/2026',status:'ALEGADO',sourceId:'quatro_nucleos',knownBy:['mara','lia','bia','jo']},
  prisao2:{title:'Nova prisão preventiva',type:'MEDIDA JUDICIAL',summary:'Uma segunda prisão preventiva foi decretada na fase que ampliou o objeto investigado.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',knownToPlayerDate:'04/03/2026',publishedDate:'04/03/2026',status:'DOCUMENTADO',sourceId:'quatro_nucleos',knownBy:['mara','lia','bia','jo']},
  pagamentos:{title:'Planilha de pagamentos alegados',type:'EXTRAÇÃO',summary:'Valores, datas e destinatários aparecem associados pela investigação a contatos do grupo chamado “A Turma”.',eventDate:'2024–2026',documentDate:'13/05/2026',knownToPFDate:'13/05/2026',knownToPlayerDate:'14/05/2026',publishedDate:'14/05/2026',status:'ALEGADO',sourceId:'turma_meninos',knownBy:['mara','lia','bia','jo']},
  visitas:{title:'Registro de visitante',type:'REGISTRO',summary:'Uma entrada registrada permite comparar nome, data e local com outros rastros da investigação.',eventDate:'06/04/2024',documentDate:'06/04/2024',knownToPFDate:'13/05/2026',knownToPlayerDate:'14/05/2026',publishedDate:'14/05/2026',status:'DOCUMENTADO',sourceId:'turma_meninos',knownBy:['mara','lia','bia','jo']},
  sictag:{title:'Contato salvo como “Sicário”',type:'MENSAGEM',summary:'O codinome reaparece em registros diferentes. A identidade e a função atribuída exigem cruzamento; o apelido sozinho não basta.',eventDate:'2024–2026',documentDate:'13/05/2026',knownToPFDate:'13/05/2026',knownToPlayerDate:'14/05/2026',publishedDate:'14/05/2026',status:'ALEGADO',sourceId:'turma_meninos',knownBy:['mara','lia','bia','jo']},
  captura:{title:'Captura com identidade institucional',type:'IMAGEM EXTRAÍDA',summary:'A tela contém informação relacionada a base internacional. Aparência visual não identifica, sozinha, o sistema acessado.',eventDate:'2025–2026',documentDate:'13/05/2026',knownToPFDate:'13/05/2026',knownToPlayerDate:'14/05/2026',publishedDate:'2026',status:'ALEGADO',sourceId:'turma_meninos',knownBy:['mara','lia','jo']},
  metadata:{title:'Metadados preservados',type:'LAUDO',summary:'O arquivo foi situado em dispositivo e horário. Isso demonstra a presença do arquivo, não o caminho técnico que o produziu.',eventDate:'2025–2026',documentDate:'13/05/2026',knownToPFDate:'13/05/2026',knownToPlayerDate:'14/05/2026',publishedDate:'2026',status:'DOCUMENTADO',sourceId:'turma_meninos',knownBy:['mara','lia','jo']},
  respostaInterpol:{title:'Resposta institucional',type:'OFÍCIO',summary:'A interface não correspondia aos mecanismos de consulta oferecidos diretamente pela Interpol; outra base apoiada em seus dados seguia possível.',eventDate:'2026',documentDate:'2026',knownToPFDate:'2026',knownToPlayerDate:'2026',publishedDate:'2026',status:'CONTESTADO',sourceId:'turma_meninos',knownBy:['mara','lia','jo']},
  pet:{title:'Questão de ordem — Pet 16662',type:'SESSÃO PÚBLICA',summary:'Em 15 de setembro houve pedido de vista durante discussão sobre tramitação conjunta. O mérito não foi julgado.',eventDate:'15/09/2026',documentDate:'15/09/2026',knownToPFDate:'15/09/2026',knownToPlayerDate:'15/09/2026',publishedDate:'15/09/2026',status:'PENDENTE',sourceId:'plenaria',knownBy:['mara','lia','jo']},
  drive:{title:'Cópia de aproximadamente 500 GB',type:'MÍDIA FORENSE',summary:'Gabinetes pediram auxílio técnico à PF para a cópia. Custódia, acesso e procedimento ainda exigiam definição institucional.',eventDate:'19/09/2026',documentDate:'19/09/2026',knownToPFDate:'19/09/2026',knownToPlayerDate:'19/09/2026',publishedDate:'19/09/2026',status:'PENDENTE',sourceId:'copia500',knownBy:['mara','lia','jo']}
 },
 scenes:[
  {id:'cold',chapter:'PRÓLOGO',title:'22H04',date:'17 NOV 2025 · GUARULHOS',bg:'assets/hangar.webp',question:'O que entra no registro desta noite?',intro:[['lia','Mara. Portão 312.'],['mara','Vi.'],['lia','Confere a ordem e fecha o registro. Sem adivinhar motivo.']],objects:[['mandado','Pasta da equipe',24,61],['voo','Painel de embarque',71,30]],puzzle:{type:'brief',prompt:'Monte o registro operacional',slots:[{id:'measure',label:'MEDIDA',accept:['mandado']},{id:'action',label:'SITUAÇÃO OBSERVÁVEL',accept:['voo']},{id:'intent',label:'INTENÇÃO',accept:['unknown']}],tokens:[['mandado','prisão autorizada'],['voo','embarque para Dubai'],['unknown','não demonstrada'],['fuga','fuga confirmada']]},outcome:'A equipe pode afirmar quem prendeu, sob qual ordem e qual viagem existia. A intenção não está no cartão de embarque.',next:'mau',hints:['Separe o que a equipe executa do que ela interpreta.','Uma viagem tem destino e horário. Onde estaria registrada a intenção?','Preencha “intenção” com o limite da prova.']},
  {id:'mau',chapter:'CAPÍTULO 1',title:'O mau cheiro',date:'2024 · SALA OPERACIONAL',bg:'assets/office.webp',question:'Onde os dois arquivos deixam de contar a mesma história?',intro:[['bia','Chegou um recorte do Banco Central. Uma carteira.'],['mara','Qual o tamanho?'],['bia','Três páginas. Duas versões. O café pode esperar.']],objects:[['planilha','Relação de cessão',26,43],['origem','Arquivo de formação',69,47],['oficioBC','Ofício do BC',47,71]],puzzle:{type:'compare',prompt:'Recorte dramatizado · encoste nos campos que se contradizem',left:{title:'RELAÇÃO DE CESSÃO · COMPOSTO',rows:[['id','ID','L47-009'],['owner','ORIGEM','TIRRENO'],['date','FORMAÇÃO','12 JUL'],['total','TOTAL','R$ 1,8 mi']]},right:{title:'ARQUIVO DE FORMAÇÃO · COMPOSTO',rows:[['id','ID','L47-009'],['owner','ORIGEM','MASTER'],['date','FORMAÇÃO','03 JUL'],['total','TOTAL','R$ 1,8 mi']]},accept:[['owner'],['owner','date']]},outcome:'O identificador e o total coincidem. Origem e cronologia, não. É uma divergência investigável, ainda não a explicação do caso.',next:'fantasma',hints:['Comece pelo que coincide. Isso reduz a divergência.','Compare um atributo da carteira, não o tamanho do número.','Origem é o primeiro campo útil; a data reforça a diferença.']},
  {id:'fantasma',chapter:'CAPÍTULO 2',title:'A carteira fantasma',date:'30 DEZ 2025 · OITIVA',bg:'assets/interview.webp',question:'Qual resposta não alcança a cadeia documental?',intro:[['lia','Uma pergunta por vez.'],['mara','Origem, formação, cessão.'],['lia','Se ele mudar de assunto, você volta à data.']],objects:[['tirreno','Instrumento de origem',23,64],['brb','Registro de cessão',75,63],['fala','Transcrição da oitiva',50,36]],puzzle:{type:'interview',prompt:'Pressione uma frase. Depois, apresente o registro que a estreita.',statements:[{id:'macro',text:'“Eu participava das decisões maiores. A operação passava pelas áreas.”'},{id:'premissa',text:'“A pergunta junta a origem da carteira com a cessão posterior.”'},{id:'memoria',text:'“Essa data exata eu não consigo recuperar de memória.”'}],correct:'premissa',evidence:['tirreno','brb','origem'],acceptedSets:[['premissa','tirreno'],['premissa','brb'],['premissa','origem']],wrong:{macro:'A resposta fala de função. A pergunta era sobre a sequência do documento.',memoria:'A falta de memória não contradiz um registro por si só.',evidence:'“Certo. Mas onde esse papel contradiz o que eu disse?” A linha continua aberta.'}},outcome:'A resposta fica mais estreita: separar operação e cessão não resolve quem sustentava a origem declarada naquela data.',next:'retorno',hints:['Procure a frase que altera o enquadramento da pergunta.','A contradição envolve origem e sequência documental.','Pressione a contestação de premissa e apresente um documento da cadeia.']},
  {id:'retorno',chapter:'CAPÍTULO 3',title:'22H04, revisto',date:'17–25 NOV 2025',bg:'assets/hangar.webp',question:'O que mudou quando os dias seguintes chegaram?',intro:[['bia','O Banco Central publicou o ato.'],['mara','Dezoito de novembro.'],['bia','Isso. A impressora prefere “amanhã”. Eu prefiro data.']],objects:[['mandado','Ordem executada',24,61],['voo','Embarque',71,30],['liquidacao','Ato do Banco Central',51,68],['defesa','Manifestação posterior',84,55]],puzzle:{type:'timeline',prompt:'Ordene pelo acontecimento, sem transformar proximidade em causa',cards:[['mandado','17 NOV · prisão'],['voo','17 NOV · embarque previsto'],['liquidacao','18 NOV · liquidação'],['defesa','25 NOV · versão da defesa']],accept:['mandado','voo','liquidacao','defesa'],ties:[['mandado','voo']]},outcome:'Prisão e embarque pertencem à mesma noite; a ordem entre eles é operacional. Liquidação e manifestação vieram depois. Uma data próxima não prova intenção.',next:'vidro',hints:['Use a data do acontecimento.','Dois itens dividem a mesma noite e podem trocar de posição.','A liquidação é do dia 18; a manifestação, do dia 25.']},
  {id:'vidro',chapter:'CAPÍTULO 4',title:'A caixa de vidro',date:'12–19 FEV 2026',bg:'assets/stf-office.webp',question:'Qual sequência alterou o trabalho da perícia?',intro:[['jo','Cem aparelhos, aproximadamente. Nenhum ficou mais jovem esperando.'],['lia','Atos anteriores continuam. Relatoria nova.'],['mara','E o despacho do dia dezenove?'],['jo','Esse eu consigo executar.']],objects:[['notaSTF','Nota institucional',26,42],['redistribuicao','Registro processual',50,62],['fluxo','Despacho pericial',74,44]],puzzle:{type:'timeline',prompt:'Reconstrua a cadeia processual',cards:[['notaSTF','12 FEV · atos mantidos'],['redistribuicao','12 FEV · redistribuição'],['fluxo','19 FEV · fluxo pericial']],accept:['notaSTF','redistribuicao','fluxo'],ties:[]},outcome:'A relatoria muda e um despacho posterior define como perícias e diligências ordinárias podem seguir.',next:'genero',hints:['A nota diz o que permanece; o registro diz quem recebe; o despacho muda o trabalho.','Dois fatos são do dia 12.','Atos mantidos → redistribuição → fluxo pericial.']},
  {id:'genero',chapter:'CAPÍTULO 5',title:'Quatro pastas',date:'04 MAR 2026 · NOVA FASE',bg:'assets/pf-lab.webp',question:'Como o material ampliou a hipótese investigativa?',intro:[['bia','Minha carteira virou quatro caixas.'],['jo','Uma delas tem logs. Outra tem gente olhando para jornalista.'],['lia','São núcleos descritos pela PF. Escrevam “segundo a investigação”.']],objects:[['financeiro','Carteiras',22,59],['institucional','Contato institucional',42,41],['ocultacao','Cadeia patrimonial',64,62],['intimidacao','Monitoramento',79,38],['prisao2','Nova ordem',51,73]],puzzle:{type:'sort',prompt:'Arquive cada rastro no núcleo descrito pela PF',bins:[['n1','FINANCEIRO'],['n2','CORRUPÇÃO INSTITUCIONAL'],['n3','OCULTAÇÃO / LAVAGEM'],['n4','INTIMIDAÇÃO / OBSTRUÇÃO']],cards:[['financeiro','carteiras e cessões','n1'],['institucional','contato com agente público','n2'],['ocultacao','cadeia patrimonial','n3'],['intimidacao','monitoramento e pressão','n4']]},outcome:'A segunda prisão pertence a uma nova fase. O problema financeiro permanece, mas já não contém sozinho o objeto investigado.',branch:true,hints:['Os núcleos descrevem hipóteses, não pessoas culpadas.','Comece pelas caixas com linguagem concreta: carteiras e patrimônio.','Carteiras → financeiro; contato público → institucional; patrimônio → ocultação; pressão → obstrução.']},
  {id:'turma',chapter:'CAPÍTULO 6A',title:'A Turma',date:'14 MAI 2026 · RASTROS',bg:'assets/office.webp',question:'Quais registros justificam tratar o codinome como o mesmo nó?',intro:[['bia','“Sicário” aparece três vezes.'],['mara','Apelido não tem CPF.'],['bia','Por isso eu trouxe data, nome e visita. Escolhe a ponte.']],objects:[['pagamentos','Pagamentos alegados',25,43],['visitas','Livro de visitas',72,57],['sictag','Contato “Sicário”',52,31]],puzzle:{type:'links',prompt:'Toque em dois registros para testar uma conexão',nodes:['pagamentos','visitas','sictag'],accept:[['pagamentos','sictag'],['visitas','sictag'],['pagamentos','visitas']],needed:2},outcome:'Dois cruzamentos independentes fazem o codinome reaparecer como nó. A função atribuída continua sendo alegação da investigação.',lead:'turma',hints:['Procure duas pontes independentes.','Uma ponte pode usar codinome; a outra deve usar nome, data ou local.','Conecte o codinome a dois registros diferentes.']},
  {id:'meninos',chapter:'CAPÍTULO 6B',title:'Os Meninos',date:'MAI 2026 · PERÍCIA DIGITAL',bg:'assets/pf-lab.webp',question:'Até onde a evidência permite ir?',intro:[['mara','Tem o nome da Interpol na tela.'],['jo','Tem uma imagem com um nome.'],['mara','Você faz isso de propósito.'],['jo','Faço laudo de propósito.']],objects:[['captura','Captura extraída',24,47],['metadata','Metadados',52,65],['respostaInterpol','Resposta institucional',78,39]],puzzle:{type:'ladder',prompt:'Marque a afirmação mais forte ainda sustentada pelo conjunto',rungs:[['file','O arquivo existia no dispositivo.'],['related','O material sugere acesso a informação relacionada.'],['direct','O acesso ocorreu diretamente em mecanismo da Interpol.'],['hack','A Interpol foi invadida.']],accept:'related',requires:['captura','metadata','respostaInterpol']},outcome:'A resposta institucional impede saltar da informação exibida para a origem técnica do acesso.',lead:'meninos',hints:['A aparência de uma tela é uma pista, não uma arquitetura.','Use metadados para situar o arquivo e a resposta para limitar a origem.','Pare em “informação relacionada”.']},
  {id:'final',chapter:'CAPÍTULO FINAL',title:'Destino em branco',date:'15–19 SET 2026',bg:'assets/pf-lab.webp',question:'O que a equipe pode fazer sem fingir que o conflito terminou?',intro:[['jo','Cópia conferida. Aproximadamente quinhentos gigabytes.'],['lia','Os gabinetes pediram apoio técnico.'],['mara','Destino?'],['lia','Ainda não preenche.']],objects:[['pet','Andamento da Pet 16662',29,42],['drive','Mídia forense',69,57]],puzzle:{type:'custody',prompt:'Feche o termo de custódia',slots:[{id:'integrity',label:'INTEGRIDADE',accept:['sealed']},{id:'destination',label:'DESTINO PROCESSUAL',accept:['pending']},{id:'merit',label:'MÉRITO EM 15/09',accept:['notjudged']}],tokens:[['sealed','cópia preservada'],['pending','pendente de definição'],['notjudged','não julgado'],['sent','encaminhado definitivamente'],['judged','julgado pelo Plenário']]},outcome:'A cópia permanece preservada. O campo de destino continua aberto.',end:true,hints:['Custódia pode ser preservada sem destino definido.','Pedido de vista não equivale a julgamento de mérito.','Use “cópia preservada”, “pendente de definição” e “não julgado”.']}
 ]
};
