window.MASTER_CASE={
 evidence:{
  mandado:{title:'Mandado em execução',type:'MEDIDA JUDICIAL',summary:'Ordem judicial válida para a primeira prisão, executada em Guarulhos.',eventDate:'17/11/2025',documentDate:'17/11/2025',knownToPFDate:'17/11/2025',publishedDate:'18/11/2025',status:'DOCUMENTADO',sourceId:'prisao1'},
  voo:{title:'Registro de embarque',type:'REGISTRO',summary:'A viagem para Dubai estava programada. O registro demonstra destino e horário, não a intenção subjetiva.',eventDate:'17/11/2025',documentDate:'17/11/2025',knownToPFDate:'17/11/2025',publishedDate:'18/11/2025',status:'DOCUMENTADO',sourceId:'prisao1'},
  defesa:{title:'Versão da defesa',type:'MANIFESTAÇÃO',summary:'A defesa sustentou que a viagem se ligava a negociação comercial e venda do banco.',eventDate:'17/11/2025',documentDate:'25/11/2025',knownToPFDate:'25/11/2025',publishedDate:'25/11/2025',status:'CONTESTADO',sourceId:'defesa_viagem'},
  loteA:{title:'Planilha de créditos — lote A',type:'REGISTRO FINANCEIRO',summary:'A planilha de cessão apresenta data e origem declarada para um conjunto de créditos.',eventDate:'2024',documentDate:'2024',knownToPFDate:'2024',publishedDate:'',status:'DOCUMENTADO',sourceId:'bc_comunicacao'},
  loteB:{title:'Arquivo de origem — lote A',type:'REGISTRO FINANCEIRO',summary:'O arquivo atribui origem e cronologia diferentes ao mesmo identificador de carteira.',eventDate:'2024',documentDate:'2024',knownToPFDate:'2024',publishedDate:'',status:'DOCUMENTADO',sourceId:'bc_comunicacao'},
  oficioBC:{title:'Comunicação institucional',type:'OFÍCIO',summary:'Inconsistências nas cessões Master/BRB foram registradas institucionalmente e comunicadas às autoridades.',eventDate:'2024',documentDate:'2024',knownToPFDate:'2024',publishedDate:'',status:'DOCUMENTADO',sourceId:'bc_comunicacao'},
  tirreno:{title:'Documento de origem Tirreno',type:'CONTRATO',summary:'Documento usado para examinar a origem declarada dos créditos posteriormente cedidos.',eventDate:'2024–2025',documentDate:'2025',knownToPFDate:'2025',publishedDate:'2026',status:'ALEGADO',sourceId:'oitiva1'},
  brb:{title:'Registro de cessão ao BRB',type:'CESSÃO',summary:'Registro identifica carteira, data e valor da cessão; sua origem é ponto de controvérsia.',eventDate:'2025',documentDate:'2025',knownToPFDate:'2025',publishedDate:'2026',status:'DOCUMENTADO',sourceId:'oitiva1'},
  fala:{title:'Trecho da oitiva',type:'DEPOIMENTO',summary:'Vorcaro descreve atuação macro e atribui etapas operacionais à equipe; a memória declarada varia por detalhe.',eventDate:'30/12/2025',documentDate:'30/12/2025',knownToPFDate:'30/12/2025',publishedDate:'29/01/2026',status:'CONTESTADO',sourceId:'oitiva1'},
  notaSTF:{title:'Nota dos dez ministros',type:'NOTA INSTITUCIONAL',summary:'Preservou atos anteriores, registrou atendimento a pedidos e informou livre redistribuição a pedido do relator.',eventDate:'12/02/2026',documentDate:'12/02/2026',knownToPFDate:'12/02/2026',publishedDate:'12/02/2026',status:'DOCUMENTADO',sourceId:'stf_nota'},
  fluxo:{title:'Despacho de 19 de fevereiro',type:'DECISÃO',summary:'Perícia de cerca de cem dispositivos segue fluxo ordinário; novas diligências independem de autorização quando assim previsto.',eventDate:'19/02/2026',documentDate:'19/02/2026',knownToPFDate:'19/02/2026',publishedDate:'19/02/2026',status:'DOCUMENTADO',sourceId:'mendonca_fluxo'},
  nucleos:{title:'Representação: quatro núcleos',type:'RELATÓRIO POLICIAL',summary:'A PF descreveu núcleos financeiro, de corrupção institucional, de ocultação/lavagem e de intimidação/obstrução.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',publishedDate:'04/03/2026',status:'ALEGADO',sourceId:'quatro_nucleos'},
  prisao2:{title:'Segunda prisão preventiva',type:'MEDIDA JUDICIAL',summary:'Nova prisão preventiva foi decretada em fase distinta, com objeto investigativo ampliado.',eventDate:'04/03/2026',documentDate:'04/03/2026',knownToPFDate:'04/03/2026',publishedDate:'04/03/2026',status:'DOCUMENTADO',sourceId:'quatro_nucleos'},
  pagamentos:{title:'Mensagens sobre pagamentos',type:'EXTRAÇÃO',summary:'Mensagens transcritas pela investigação associam pagamentos alegados a pessoas e grupos; não são sentença.',eventDate:'2024–2026',documentDate:'13/05/2026',knownToPFDate:'2026',publishedDate:'14/05/2026',status:'ALEGADO',sourceId:'turma_meninos'},
  visitas:{title:'Registro de visitante',type:'REGISTRO',summary:'Entrada registrada conecta um nome já visto em mensagens a um episódio examinado pela PF.',eventDate:'06/04/2024',documentDate:'06/04/2024',knownToPFDate:'2026',publishedDate:'14/05/2026',status:'DOCUMENTADO',sourceId:'turma_meninos'},
  sictag:{title:'Codinome “Sicário”',type:'MENSAGEM',summary:'O mesmo codinome aparece em registros de contato e pagamentos alegados examinados pela PF.',eventDate:'2024–2026',documentDate:'2026',knownToPFDate:'2026',publishedDate:'14/05/2026',status:'ALEGADO',sourceId:'turma_meninos'},
  captura:{title:'Captura com identidade institucional',type:'IMAGEM EXTRAÍDA',summary:'A aparência remete a dados internacionais, mas a imagem isolada não demonstra qual sistema foi acessado.',eventDate:'2025–2026',documentDate:'2026',knownToPFDate:'2026',publishedDate:'2026',status:'ALEGADO',sourceId:'turma_meninos'},
  metadata:{title:'Metadados do arquivo',type:'LAUDO',summary:'Horário, dispositivo e proveniência permitem situar o arquivo, mas não provam por si um ataque ao sistema exibido.',eventDate:'2025–2026',documentDate:'2026',knownToPFDate:'2026',publishedDate:'2026',status:'DOCUMENTADO',sourceId:'turma_meninos'},
  respostaInterpol:{title:'Esclarecimento sobre a interface',type:'RESPOSTA INSTITUCIONAL',summary:'A identidade visual não corresponde aos mecanismos de consulta diretamente disponibilizados pela Interpol; outra origem permaneceu possível.',eventDate:'2026',documentDate:'2026',knownToPFDate:'2026',publishedDate:'2026',status:'CONTESTADO',sourceId:'turma_meninos'},
  pet:{title:'Questão de ordem — Pet 16662',type:'SESSÃO PÚBLICA',summary:'O Plenário discutiu tramitação conjunta; pedido de vista suspendeu a análise sem julgamento do mérito.',eventDate:'15/09/2026',documentDate:'15/09/2026',knownToPFDate:'15/09/2026',publishedDate:'15/09/2026',status:'PENDENTE',sourceId:'plenaria'},
  drive:{title:'Cópia de aproximadamente 500 GB',type:'MÍDIA FORENSE',summary:'Gabinetes solicitaram auxílio técnico da PF para acesso à cópia, mantendo aberto o conflito sobre custódia e tratamento.',eventDate:'19/09/2026',documentDate:'19/09/2026',knownToPFDate:'19/09/2026',publishedDate:'19/09/2026',status:'PENDENTE',sourceId:'copia500'}
 },
 scenes:[
  {id:'cold',chapter:'PRÓLOGO',title:'22H04',date:'17 NOV 2025 · GUARULHOS',bg:'assets/hangar.webp',intro:[['COORDENADORA','A equipe do portão confirmou. O mandado está vigente.'],['INVESTIGADORA','E a viagem?'],['COORDENADORA','Existe. A intenção é outra pergunta. Não misture as duas.']],hotspots:[['mandado','Mandado',25,58],['voo','Painel de embarque',69,31],['defesa','Nota posterior da defesa',82,67]],question:'O que os registros permitem afirmar sobre a viagem?',answers:[['fuga','A viagem demonstra que ele pretendia fugir.'],['limite','A viagem estava programada; a intenção permaneceu disputada.']],accepted:'limite',sets:[['mandado','voo'],['voo','defesa']],outcome:'A prisão acontece. O destino está no registro; a finalidade não.',next:'mau'},
  {id:'mau',chapter:'CAPÍTULO 1',title:'O mau cheiro',date:'2024 · SALA OPERACIONAL',bg:'assets/office.webp',intro:[['ANALISTA','Mandaram um recorte pequeno. Um lote, duas origens.'],['INVESTIGADORA','Pequeno costuma caber na agenda.'],['ANALISTA','Na agenda, sim. Na planilha eu não prometo.']],hotspots:[['loteA','Planilha de cessão',27,42],['loteB','Arquivo de origem',66,49],['oficioBC','Ofício institucional',48,73]],question:'Esses registros descrevem a mesma carteira da mesma forma?',answers:[['sim','Sim. O identificador basta para tornar os registros equivalentes.'],['nao','Não. O identificador coincide, mas origem e cronologia divergem.']],accepted:'nao',sets:[['loteA','loteB'],['loteB','oficioBC']],outcome:'A diferença não prova o mecanismo inteiro. Ela abre uma linha que precisa de origem, datas e documentos.',next:'fantasma'},
  {id:'fantasma',chapter:'CAPÍTULO 2',title:'A carteira fantasma',date:'30 DEZ 2025 · OITIVA',bg:'assets/interview.webp',intro:[['COORDENADORA','Pergunte uma coisa de cada vez. Se vier contexto, traga de volta ao documento.'],['INVESTIGADORA','Origem primeiro. Execução depois.'],['COORDENADORA','E registre quando a resposta não alcança a pergunta.']],hotspots:[['tirreno','Documento Tirreno',22,65],['brb','Registro BRB',73,64],['fala','Depoimento gravado',50,35]],question:'Qual contradição merece ser levada à oitiva?',answers:[['valor','O valor alto, isoladamente, demonstra origem falsa.'],['origem','A origem declarada não fecha com a sequência documental da cessão.']],accepted:'origem',sets:[['tirreno','brb'],['loteB','brb']],outcome:'A pergunta fica mais estreita: quem tinha base documental para afirmar a origem na data da cessão?',interview:true,next:'retorno'},
  {id:'retorno',chapter:'CAPÍTULO 3',title:'22H04, pela segunda vez',date:'17–18 NOV 2025',bg:'assets/hangar.webp',intro:[['INVESTIGADORA','O painel estava aqui desde o começo.'],['ANALISTA','Agora você sabe o que ele não mostra.'],['INVESTIGADORA','E o que o mandado já carregava antes de nós chegarmos.']],hotspots:[['voo','Horário revisto',68,31],['mandado','Medida executada',25,58],['defesa','Versão anexada',82,67]],question:'Como registrar prisão, viagem e liquidação sem fabricar uma causalidade?',answers:[['junto','A liquidação no dia seguinte prova que a viagem era fuga.'],['separado','São fatos separados; versões e interpretação investigativa devem permanecer atribuídas.']],accepted:'separado',sets:[['mandado','defesa'],['voo','defesa']],outcome:'A primeira prisão fecha uma etapa. A liquidação do Banco Central, no dia seguinte, abre outra.',next:'vidro'},
  {id:'vidro',chapter:'CAPÍTULO 4',title:'A caixa de vidro',date:'28 NOV 2025 — 19 FEV 2026',bg:'assets/stf-office.webp',intro:[['COORDENADORA','O caso mudou de endereço.'],['PERITA','E de permissões. Tenho quase cem dispositivos esperando uma regra operacional.'],['INVESTIGADORA','Então o efeito da decisão é a pista.']],hotspots:[['notaSTF','Nota conjunta',27,42],['fluxo','Despacho pericial',72,48]],question:'O que mudou para a investigação em 19 de fevereiro?',answers:[['fim','O STF encerrou o controle judicial das novas frentes.'],['fluxo','A perícia ganhou fluxo ordinário; o restante continuou sujeito às regras do caso.']],accepted:'fluxo',sets:[['notaSTF','fluxo']],outcome:'Atos anteriores permanecem. A relatoria muda, e a perícia volta a andar sob novas condições.',next:'genero'},
  {id:'genero',chapter:'CAPÍTULO 5',title:'O caso muda de gênero',date:'04 MAR 2026',bg:'assets/pf-lab.webp',intro:[['PERITA','O material não ficou maior. Ficou diferente.'],['ANALISTA','Até ontem eu seguia crédito e cessão. Aqui aparecem pagamentos, contatos, acesso a informação.'],['COORDENADORA','Quatro núcleos é a hipótese da investigação. Escrevam assim.']],hotspots:[['nucleos','Relatório dos quatro núcleos',37,47],['prisao2','Nova ordem preventiva',70,63]],question:'Por que a segunda prisão não é repetição da primeira?',answers:[['mesma','Porque reforça exatamente a mesma suspeita financeira.'],['escala','Porque decorre de nova fase e de uma escala investigativa ampliada.']],accepted:'escala',sets:[['nucleos','prisao2']],outcome:'A pergunta deixou de caber só em uma carteira de crédito. Duas linhas podem ser abertas primeiro.',branch:true},
  {id:'turma',chapter:'CAPÍTULO 6A',title:'A Turma',date:'MAIO 2026 · LINHA PRESENCIAL',bg:'assets/office.webp',intro:[['ANALISTA','O apelido aparece em pagamento, contato e registro.'],['INVESTIGADORA','A mesma pessoa?'],['ANALISTA','Talvez. Os registros precisam fazer essa ponte, não o apelido.']],hotspots:[['pagamentos','Mensagens de pagamento',28,43],['visitas','Registro de visitante',72,59],['sictag','Codinome recorrente',52,31]],question:'O que conecta legitimamente os rastros?',answers:[['apelido','O codinome, sozinho, identifica e prova a função de cada pessoa.'],['convergencia','Nome, contexto, datas e registros convergem; a função atribuída continua sendo alegação da PF.']],accepted:'convergencia',sets:[['pagamentos','visitas'],['sictag','visitas'],['pagamentos','sictag']],outcome:'O codinome deixa de ser decoração: ele conecta registros independentes, sem virar veredito.',lead:'turma'},
  {id:'meninos',chapter:'CAPÍTULO 6B',title:'Os Meninos',date:'MAIO 2026 · LINHA DIGITAL',bg:'assets/pf-lab.webp',intro:[['PERITA','A captura parece convincente. Esse é o perigo.'],['INVESTIGADORA','O que ela prova?'],['PERITA','Que o arquivo existe. Para o resto, abra os metadados e leia a resposta institucional.']],hotspots:[['captura','Captura de tela',25,46],['metadata','Metadados',51,65],['respostaInterpol','Resposta institucional',77,39]],question:'Qual é a conclusão digital mais precisa?',answers:[['hack','A captura prova que a Interpol foi invadida.'],['estreita','O material sugere acesso a informação relacionada; a origem técnica exata permanece aberta.']],accepted:'estreita',sets:[['captura','metadata','respostaInterpol'],['captura','respostaInterpol']],outcome:'A precisão preserva a pista. Exagerar a conclusão destruiria o que o arquivo realmente sustenta.',lead:'meninos'},
  {id:'final',chapter:'CAPÍTULO FINAL',title:'O relatório vira o caso',date:'15–19 SET 2026',bg:'assets/pf-lab.webp',intro:[['COORDENADORA','O relatório saiu da equipe e voltou como questão de competência.'],['PERITA','E a cópia está aqui. Aproximadamente quinhentos gigabytes.'],['INVESTIGADORA','Quem examina?'],['COORDENADORA','Essa é a pergunta que ainda não fechou.']],hotspots:[['pet','Questão de ordem',31,41],['drive','Cópia forense',69,56]],question:'Qual é o estado institucional demonstrado em 19 de setembro?',answers:[['decidido','O Plenário decidiu o mérito e definiu definitivamente quem examina o material.'],['pendente','A tramitação e o tratamento do material permanecem em disputa; houve vista, não mérito final.']],accepted:'pendente',sets:[['pet','drive']],outcome:'O arquivo permanece lacrado na tela. O cursor pisca no campo de destino.',end:true}
 ],
 interview:{statements:[
  {id:'macro',text:'“Eu participava das decisões macro. A execução ficava com as equipes.”',detail:'Resposta dramatizada a partir de padrões públicos observáveis; não é citação literal.'},
  {id:'origem',text:'“A premissa da pergunta mistura a carteira com a operação seguinte.”',detail:'A resposta contesta o enquadramento e desloca para contexto.'},
  {id:'memoria',text:'“A data exata eu não vou saber de memória.”',detail:'Declaração de memória incompleta.'}
 ],correctStatement:'origem',acceptedEvidence:['tirreno','brb','loteB'],success:'A resposta fica mais específica, mas não resolve sozinha a origem. A divergência documental permanece registrada.'}
};
