(()=>{
const E=(title,type,summary,eventDate,documentDate,knownToPFDate,knownToPlayerDate,publishedDate,status,sourceId,knownBy,supports=[],contradicts=[],recontextualizes=[])=>({title,type,summary,eventDate,documentDate,knownToPFDate,knownToPlayerDate,publishedDate,status,sourceId,knownBy,supports,contradicts,recontextualizes});
window.MASTER_CASE={
 characters:{mara:{name:'MARA',role:'Investigadora',voice:118},lia:{name:'LIA',role:'Coordenadora',voice:104},bia:{name:'BIA',role:'Analista financeira',voice:132},jo:{name:'JO',role:'Perita digital',voice:140},depoente:{name:'DEPOENTE',role:'Oitiva dramatizada',voice:110},advogado:{name:'ADVOGADO',role:'Defesa',voice:100}},
 evidence:{
  mandado:E('Ordem em execução','MEDIDA JUDICIAL','A equipe tinha ordem válida para efetuar a primeira prisão em Guarulhos.','17/11/2025','17/11/2025','17/11/2025','17/11/2025','18/11/2025','DOCUMENTADO','prisao1',['mara','lia'],['prisao1']),
  voo:E('Embarque previsto','REGISTRO','Destino Dubai, portão 312, naquela noite. O registro não informa a finalidade da viagem.','17/11/2025','17/11/2025','17/11/2025','17/11/2025','18/11/2025','DOCUMENTADO','prisao1',['mara','lia'],['viagem'],[],['defesa']),
  defesa:E('Versão apresentada pela defesa','MANIFESTAÇÃO','A defesa relacionou a viagem a negociação comercial. A versão foi apresentada depois da prisão.','17/11/2025','25/11/2025','25/11/2025','25/11/2025','25/11/2025','CONTESTADO','defesa_viagem',['mara','lia'],['viagem_comercial'],['fuga_confirmada'],['voo']),
  oficioBC:E('Comunicação do Banco Central','OFÍCIO','Inconsistências nas cessões Master/BRB chegaram às autoridades por via institucional.','2024','22/07/2024','22/07/2024','22/07/2024','','DOCUMENTADO','bc_comunicacao',['mara','bia','lia'],['origem_institucional']),
  planilha:E('Relação de cessão · versão A','REGISTRO FINANCEIRO','Recorte composto: o lote L47-009 aparece com origem Tirreno, formação em 12 de julho e total de R$ 1,8 milhão.','2024','2024','2024','2024','','DRAMATIZAÇÃO','bc_comunicacao',['mara','bia','lia'],['origem_tirreno'],['origem_master']),
  origem:E('Arquivo de formação · versão B','REGISTRO FINANCEIRO','Recorte composto: o mesmo lote e total aparecem com origem Master e formação em 3 de julho.','2024','2024','2024','2024','','DRAMATIZAÇÃO','bc_comunicacao',['mara','bia','lia'],['origem_master'],['origem_tirreno']),
  historico:E('Histórico de versões','METADADO COMPOSTO','A origem foi alterada entre duas versões; o identificador e o total permaneceram iguais.','2024','2024','2024','2024','','DRAMATIZAÇÃO','bc_comunicacao',['mara','bia','lia'],['divergencia_origem'],[],['planilha','origem']),
  tirreno:E('Instrumento de origem declarada','CONTRATO','Documento usado para situar a Tirreno na origem da carteira examinada.','2024–2025','2025','2025','30/12/2025','2026','ALEGADO','oitiva1',['mara','bia','lia','depoente'],['origem_tirreno']),
  brb:E('Cessão registrada ao BRB','CESSÃO','O registro situa carteira, data e cessão; a cadeia anterior da origem continuou controvertida.','2025','2025','2025','30/12/2025','2026','DOCUMENTADO','oitiva1',['mara','bia','lia','depoente'],['cessao_brb']),
  fala:E('Trecho da oitiva','DEPOIMENTO','O depoente separa decisão geral e execução pelas áreas, contesta premissas e declara memória desigual sobre datas.','30/12/2025','30/12/2025','30/12/2025','30/12/2025','29/01/2026','CONTESTADO','oitiva1',['mara','lia','depoente'],['resposta_parcial']),
  liquidacao:E('Ato de liquidação','ATO DO BANCO CENTRAL','O Banco Central decretou a liquidação extrajudicial em 18 de novembro, fato posterior e distinto da prisão.','18/11/2025','18/11/2025','18/11/2025','18/11/2025','18/11/2025','DOCUMENTADO','liquidacao',['mara','lia','bia'],['liquidacao'],[],['voo']),
  notaSTF:E('Nota dos dez ministros','NOTA INSTITUCIONAL','Manteve atos anteriores, registrou atendimento a pedidos da PF e PGR e informou livre redistribuição a pedido do relator.','12/02/2026','12/02/2026','12/02/2026','12/02/2026','12/02/2026','DOCUMENTADO','stf_nota',['mara','lia','jo'],['atos_mantidos']),
  redistribuicao:E('Redistribuição da relatoria','REGISTRO PROCESSUAL','Os feitos foram redistribuídos e André Mendonça recebeu a relatoria.','12/02/2026','12/02/2026','12/02/2026','12/02/2026','12/02/2026','DOCUMENTADO','stf_nota',['mara','lia','jo'],['nova_relatoria']),
  fluxo:E('Despacho de 19 de fevereiro','DECISÃO','Abriu fluxo ordinário para perícias em cerca de cem dispositivos e diligências sem necessidade de autorização judicial.','19/02/2026','19/02/2026','19/02/2026','19/02/2026','19/02/2026','DOCUMENTADO','mendonca_fluxo',['mara','lia','jo'],['fluxo_pericial'],['liberacao_irrestrita']),
  financeiro:E('Carteiras e cessões','PEÇA DE ANÁLISE','Registros financeiros permanecem no núcleo financeiro descrito pela investigação.','04/03/2026','04/03/2026','04/03/2026','04/03/2026','04/03/2026','ALEGADO','quatro_nucleos',['mara','lia','bia','jo'],['nucleo_financeiro']),
  institucional:E('Contato institucional','PEÇA DE ANÁLISE','Registros foram associados pela PF ao núcleo de corrupção institucional.','04/03/2026','04/03/2026','04/03/2026','04/03/2026','04/03/2026','ALEGADO','quatro_nucleos',['mara','lia','bia','jo'],['nucleo_institucional']),
  ocultacao:E('Cadeia patrimonial','PEÇA DE ANÁLISE','Ativos e transferências foram associados pela PF ao núcleo de ocultação patrimonial e lavagem.','04/03/2026','04/03/2026','04/03/2026','04/03/2026','04/03/2026','ALEGADO','quatro_nucleos',['mara','lia','bia','jo'],['nucleo_ocultacao']),
  intimidacao:E('Monitoramento e pressão','PEÇA DE ANÁLISE','Mensagens e registros foram associados pela PF a intimidação e obstrução.','04/03/2026','04/03/2026','04/03/2026','04/03/2026','04/03/2026','ALEGADO','quatro_nucleos',['mara','lia','bia','jo'],['nucleo_intimidacao']),
  prisao2:E('Nova prisão preventiva','MEDIDA JUDICIAL','Uma segunda prisão preventiva foi decretada na fase que ampliou o objeto investigado.','04/03/2026','04/03/2026','04/03/2026','04/03/2026','04/03/2026','DOCUMENTADO','quatro_nucleos',['mara','lia','bia','jo'],['prisao2'],['repeticao_prisao1'],['mandado']),
  pagamentos:E('Pagamentos alegados','EXTRAÇÃO','Valores, datas e destinatários aparecem associados pela investigação a contatos do grupo chamado “A Turma”.','2024–2026','13/05/2026','13/05/2026','14/05/2026','14/05/2026','ALEGADO','turma_meninos',['mara','lia','bia','jo'],['ponte_presencial']),
  visitas:E('Registro de visitante','REGISTRO','Uma entrada registrada permite comparar nome, data e local com outros rastros.','06/04/2024','06/04/2024','13/05/2026','14/05/2026','14/05/2026','DOCUMENTADO','turma_meninos',['mara','lia','bia','jo'],['ponte_presencial']),
  sictag:E('Contato salvo como “Sicário”','MENSAGEM','O codinome reaparece em registros diferentes. O apelido sozinho não demonstra identidade nem função.','2024–2026','13/05/2026','13/05/2026','14/05/2026','14/05/2026','ALEGADO','turma_meninos',['mara','lia','bia','jo'],['ponte_alias'],[],['pagamentos','captura']),
  captura:E('Captura com identidade institucional','IMAGEM EXTRAÍDA','A tela contém informação relacionada a base internacional. A aparência não identifica, sozinha, o sistema acessado.','2025–2026','13/05/2026','13/05/2026','14/05/2026','2026','ALEGADO','turma_meninos',['mara','lia','jo'],['informacao_relacionada']),
  metadata:E('Metadados preservados','LAUDO','O arquivo foi situado em dispositivo e horário. Isso não demonstra o caminho técnico que o produziu.','2025–2026','13/05/2026','13/05/2026','14/05/2026','2026','DOCUMENTADO','turma_meninos',['mara','lia','jo'],['arquivo_no_dispositivo'],['origem_tecnica_provada'],['captura']),
  respostaInterpol:E('Resposta institucional','OFÍCIO','A interface não correspondia às consultas oferecidas diretamente pela Interpol; outra base apoiada em seus dados seguia possível.','2026','2026','2026','2026','2026','CONTESTADO','turma_meninos',['mara','lia','jo'],['limite_interpol'],['interpol_invadida'],['captura']),
  pet:E('Questão de ordem · Pet 16662','SESSÃO PÚBLICA','Em 15 de setembro houve pedido de vista durante discussão sobre tramitação conjunta. O mérito não foi julgado.','15/09/2026','15/09/2026','15/09/2026','15/09/2026','15/09/2026','PENDENTE','plenaria',['mara','lia','jo'],['merito_pendente'],['merito_decidido']),
  drive:E('Cópia de aproximadamente 500 GB','MÍDIA FORENSE','Gabinetes pediram auxílio técnico à PF para a cópia. A destinação institucional permanecia em definição.','19/09/2026','19/09/2026','19/09/2026','19/09/2026','19/09/2026','PENDENTE','copia500',['mara','lia','jo'],['copia_preservada'],['destino_definido'])
 },
 scenes:[
  {id:'cold',chapter:'PRÓLOGO',title:'22H04',date:'17 NOV 2025 · GUARULHOS',bg:'assets/hangar.webp',question:'O que a equipe pode registrar agora?',starter:['mandado','voo'],objects:[['mandado','Ordem',24,61],['voo','Embarque',71,30]],intro:[['lia','Portão 312. Confere o nome.'],['mara','Confere.'],['lia','Então vamos.']],actions:[
   {id:'cold-order',verb:'rastrear',title:'Conferir a ordem',detail:'Identidade, alcance e validade da medida.',result:[['mara','Nome e documento conferem.'],['lia','Registra a hora.']]},
   {id:'cold-flight',verb:'verificar',title:'Conferir o embarque',detail:'Destino e situação observável no portão.',result:[['mara','Dubai. Embarque aberto.'],['lia','É o que o painel mostra.']]},
   {id:'cold-overreach',verb:'formalizar',title:'Registrar “tentativa de fuga”',detail:'Atribuir uma intenção ao embarque.',requiresActions:['cold-flight'],fail:true,result:[['mara','Coloco risco de fuga?'],['lia','Coloca embarque previsto. Intenção não veio impressa no cartão.']]},
   {id:'cold-execute',verb:'formalizar',title:'Executar e registrar a medida',detail:'Prisão autorizada, identidade confirmada, embarque previsto.',requiresActions:['cold-order','cold-flight'],complete:true,conclusion:'SUPPORTED',result:[['lia','Pode cumprir.']]}
  ],outcome:'A prisão é executada. A viagem existe; a intenção não está demonstrada.',next:'mau',hints:['A equipe precisa agir com o que existe nesta noite.','Separe destino de motivo.','Confira ordem e embarque antes de registrar.']},
  {id:'mau',chapter:'CAPÍTULO 1',title:'O mau cheiro',date:'2024 · SALA OPERACIONAL',bg:'assets/office.webp',question:'Por que o mesmo lote tem duas origens?',starter:['oficioBC'],objects:[['oficioBC','Comunicação do BC',48,67]],intro:[['bia','O Banco Central mandou um recorte.'],['mara','De quê?'],['bia','Uma cessão. Disseram que há uma inconsistência. Não disseram qual.']],actions:[
   {id:'mau-id',verb:'rastrear',title:'Rastrear o identificador L47-009',detail:'Procurar o mesmo lote nas versões recebidas.',discover:['planilha','origem'],result:[['bia','Duas entradas. Mesmo lote, mesmo total.'],['mara','E duas datas.']]},
   {id:'mau-origin',verb:'rastrear',title:'Rastrear a origem “Tirreno”',detail:'Seguir a origem declarada em vez do valor.',discover:['planilha','origem'],result:[['bia','Encontrei o lote. Na outra versão, a origem é Master.']]},
   {id:'mau-total',verb:'verificar',title:'Recalcular o total',detail:'Testar se a divergência está no valor da carteira.',discover:['planilha','origem'],result:[['bia','Um milhão e oitocentos nas duas.'],['mara','Ótimo. Um suspeito a menos.']]},
   {id:'mau-history',verb:'verificar',title:'Pedir o histórico das versões',detail:'Comparar o que mudou e o que permaneceu.',requiresAnyActions:['mau-id','mau-origin','mau-total'],discover:['historico'],recontextualize:['planilha','origem'],result:[['bia','Origem e data mudaram. Identificador e total ficaram.'],['mara','Quem alterou?'],['bia','Ainda não sei.']]},
   {id:'mau-absence',verb:'formalizar',title:'Concluir que os créditos não existiam',detail:'Tratar a divergência documental como prova de inexistência.',requiresAnyEvidence:['planilha','origem'],fail:true,result:[['mara','A carteira é inexistente.'],['bia','Pode ser. Estes arquivos não provam isso. Provam que a origem mudou.']]},
   {id:'mau-gap',verb:'formalizar',title:'Registrar divergência de origem',detail:'Mesmo lote e total; origem e cronologia incompatíveis. Pedir a cadeia documental.',requiresAnyActions:['mau-history','mau-origin'],complete:true,conclusion:'SUPPORTED',result:[['mara','Registra a divergência e pede a formação da carteira.'],['bia','Agora temos uma pergunta que alguém precisa responder.']]}
  ],outcome:'Os registros não contam a mesma história sobre a origem. A existência e a autoria da alteração continuam abertas.',next:'fantasma',hints:['O número alto chama atenção. O que identifica a mesma carteira?','Procure um campo que mudou entre versões.','Rastreie o lote ou a origem; depois peça o histórico.']},
  {id:'fantasma',chapter:'CAPÍTULO 2',title:'A carteira fantasma',date:'30 DEZ 2025 · OITIVA',bg:'assets/interview.webp',question:'Quem consegue sustentar a origem declarada?',starter:['tirreno','brb','fala'],objects:[['tirreno','Instrumento',23,64],['brb','Cessão',75,63],['fala','Transcrição',50,36]],intro:[['lia','Tem quarenta minutos.'],['mara','Eu preciso da sequência.'],['lia','Ele não precisa gostar da pergunta. Só precisa entender.']],actions:[
   {id:'fan-macro',verb:'confrontar',title:'Perguntar quem executava a operação',detail:'Abrir pela divisão entre decisão macro e trabalho das áreas.',result:[['mara','Quem montava a carteira?'],['depoente','As áreas faziam a execução. Eu acompanhava o banco num nível mais geral.'],['mara','Qual área?'],['depoente','Eu não quero arriscar um nome agora.']]},
   {id:'fan-date',verb:'confrontar',title:'Fixar a data de formação',detail:'Pedir a sequência sem apresentar ainda o histórico.',result:[['mara','A carteira foi formada dia três ou dia doze?'],['depoente','Eu não consigo cravar essa data de memória.'],['advogado','Se há um documento, ele pode ser apresentado.']]},
   {id:'fan-reveal',verb:'confrontar',title:'Apresentar as versões da origem',detail:'Mostrar que a origem muda enquanto o lote permanece.',requiresAnyEvidence:['historico','origem'],recontextualize:['historico','tirreno'],result:[['mara','O identificador não muda. A origem muda. Quem validou a segunda versão?'],['depoente','Eu preciso separar duas coisas. A cessão ao BRB veio depois.'],['mara','Eu perguntei sobre a origem antes da cessão.'],['depoente','Essa formação passava pelas áreas. Eu não consigo atribuir daqui.']]},
   {id:'fan-wrong',verb:'confrontar',title:'Apresentar apenas a cessão ao BRB',detail:'Usar o destino da carteira para perguntar sobre sua origem.',fail:true,result:[['mara','A cessão ao BRB contradiz sua resposta.'],['depoente','Não. Esse é o destino da carteira. Você perguntou da origem.'],['mara','Certo. Volto um passo.']]},
   {id:'fan-close',verb:'formalizar',title:'Registrar a lacuna da cadeia',detail:'A resposta separa cessão e origem, mas não identifica quem sustentou a origem alterada.',requiresActions:['fan-reveal'],complete:true,conclusion:'INCOMPLETE',result:[['lia','Conseguiu um nome?'],['mara','Não. Consegui uma lacuna mais estreita.'],['lia','Serve.']]}
  ],outcome:'A oitiva não resolve a origem. Ela delimita onde a cadeia deixa de ser sustentada.',next:'retorno',hints:['A cessão é posterior à formação.','Uma resposta sobre função não resolve a sequência do documento.','Mostre o histórico e volte à origem anterior à cessão.']},
  {id:'retorno',chapter:'CAPÍTULO 3',title:'22H04, pela segunda vez',date:'17–25 NOV 2025',bg:'assets/hangar.webp',question:'O que os fatos posteriores permitem — e não permitem — inferir?',starter:['mandado','voo','liquidacao','defesa'],objects:[['mandado','Ordem executada',24,61],['voo','Embarque',71,30],['liquidacao','Ato do BC',51,68],['defesa','Manifestação',84,55]],intro:[['bia','Ato do Banco Central: dia dezoito.'],['mara','A prisão foi na noite anterior.'],['bia','E a manifestação da defesa veio uma semana depois. Minha impressora juntou tudo na mesma bandeja.']],actions:[
   {id:'ret-dates',verb:'verificar',title:'Separar as quatro datas',detail:'Acontecimento, documento, publicação e ciência da equipe.',recontextualize:['voo'],result:[['bia','Prisão e embarque: dia dezessete. Liquidação: dezoito. Defesa: vinte e cinco.']]},
   {id:'ret-defense',verb:'rastrear',title:'Localizar a primeira versão da defesa',detail:'Ver quando a finalidade comercial entrou no registro público.',result:[['mara','Essa explicação não existia para a equipe no portão.'],['bia','Agora existe. Sem viajar no tempo, por favor.']]},
   {id:'ret-cause',verb:'formalizar',title:'Ligar os fatos como uma causa única',detail:'Converter proximidade temporal em intenção demonstrada.',fail:true,result:[['mara','A sequência prova a fuga antes da liquidação.'],['bia','A sequência prova a sequência. O motivo ainda está em disputa.']]},
   {id:'ret-limit',verb:'formalizar',title:'Registrar fatos e versões separadamente',detail:'Prisão, liquidação, interpretação investigativa e versão defensiva em campos distintos.',requiresActions:['ret-dates','ret-defense'],complete:true,conclusion:'CONTESTED',result:[['mara','Quatro linhas. Nenhuma entra na cabeça de ninguém.'],['bia','A impressora vai odiar.']]}
  ],outcome:'O retorno acrescenta contexto, não certeza sobre intenção.',next:'vidro',hints:['Quando cada informação ficou disponível?','A versão comercial não estava no cold open.','Separe evento, ato posterior e versões sobre a viagem.']},
  {id:'vidro',chapter:'CAPÍTULO 4',title:'A caixa de vidro',date:'12–19 FEV 2026',bg:'assets/stf-office.webp',question:'Qual trabalho pode seguir sem extrapolar a decisão?',starter:['notaSTF','redistribuicao'],objects:[['notaSTF','Nota institucional',26,42],['redistribuicao','Registro processual',52,62]],intro:[['jo','Os aparelhos continuam aqui.'],['lia','Atos mantidos. Relatoria redistribuída.'],['jo','Isso responde quem assina. Não responde o que eu posso abrir hoje.']],actions:[
   {id:'vid-request',verb:'verificar',title:'Pedir o alcance operacional',detail:'Transformar a mudança processual em uma pergunta executável.',discover:['fluxo'],result:[['jo','Dia dezenove. Perícia ordinária e diligência que não dependa de nova autorização.'],['lia','As outras continuam pelo caminho próprio.']]},
   {id:'vid-openall',verb:'formalizar',title:'Liberar todos os cem dispositivos',detail:'Tratar fluxo ordinário como autorização irrestrita.',requiresEvidence:['fluxo'],fail:true,result:[['mara','Então abre tudo.'],['jo','Não foi isso que chegou. Eu separo o que cabe no fluxo. O resto espera.']]},
   {id:'vid-map',verb:'rastrear',title:'Mapear diligência e autorização',detail:'Separar perícia ordinária, nova medida e item pendente.',requiresEvidence:['fluxo'],result:[['lia','Agora temos três filas.'],['jo','Melhor que uma fila com cem desculpas.']]},
   {id:'vid-close',verb:'formalizar',title:'Abrir o fluxo cabível',detail:'Executar perícias ordinárias e preservar pedidos que exigem decisão própria.',requiresActions:['vid-request','vid-map'],complete:true,conclusion:'SUPPORTED',result:[['lia','Protocola.'],['jo','Já comecei pelos que não dependem de despacho novo.']]}
  ],outcome:'A investigação volta a andar sob uma nova cadeia de decisões.',next:'genero',hints:['A nota institucional não é uma ordem técnica de perícia.','Procure o ato que muda o trabalho da equipe.','Peça o alcance e separe o que exige nova autorização.']},
  {id:'genero',chapter:'CAPÍTULO 5',title:'O caso muda de gênero',date:'04 MAR 2026 · NOVA FASE',bg:'assets/pf-lab.webp',question:'O que torna esta fase diferente da primeira prisão?',starter:['prisao2'],objects:[['prisao2','Nova prisão preventiva',49,63]],intro:[['bia','Chegou outra preventiva.'],['mara','Pelo mesmo fato?'],['jo','Abri uma extração esperando contrato. Tem monitoramento, acesso a dado e gente perguntando por jornalista.']],actions:[
   {id:'gen-fin',verb:'rastrear',title:'Seguir a carteira original',detail:'Ver onde a frente financeira reaparece.',discover:['financeiro','ocultacao'],result:[['bia','Financeiro continua. Agora há uma cadeia patrimonial ao lado.']]},
   {id:'gen-info',verb:'rastrear',title:'Seguir quem buscava informação',detail:'Localizar registros de contato, monitoramento e acesso alegado.',discover:['institucional','intimidacao'],result:[['jo','Contato institucional numa pasta. Monitoramento em outra. A fronteira ficou pior.']]},
   {id:'gen-repeat',verb:'formalizar',title:'Tratar a nova prisão como repetição',detail:'Registrar a fase como continuação idêntica da frente financeira.',fail:true,result:[['mara','Outra prisão pelo mesmo caso.'],['lia','Mesmo caso, novo fundamento e objeto ampliado. Não encurta isso.']]},
   {id:'gen-scale',verb:'formalizar',title:'Registrar a ampliação do objeto',detail:'Segundo a PF, quatro núcleos orientam a investigação; isso não equivale a quatro condenações.',requiresActions:['gen-fin','gen-info'],complete:true,branch:true,conclusion:'SUPPORTED',recontextualize:['mandado','prisao2'],result:[['lia','No relatório: “segundo a investigação”.'],['mara','Em todas as quatro linhas.']]}
  ],outcome:'A segunda prisão marca uma investigação maior, não a repetição da primeira.',hints:['Compare o objeto desta fase com a carteira do início.','Siga uma trilha financeira e uma informacional.','Abra as duas frentes antes de formalizar.']},
  {id:'turma',chapter:'CAPÍTULO 6',title:'A Turma',date:'14 MAI 2026',bg:'assets/office.webp',question:'O codinome é o mesmo nó ou apenas o mesmo apelido?',starter:['sictag'],objects:[['sictag','Contato extraído',48,39]],intro:[['bia','“Sicário”. Ótimo nome para gerar convicção antes de prova.'],['mara','Procura fora da agenda.'],['bia','Nome civil, data, local. Coisas sem trilha sonora.']],actions:[
   {id:'tur-pay',verb:'rastrear',title:'Rastrear destinatários e datas',detail:'Procurar o contato nos pagamentos alegados.',discover:['pagamentos'],result:[['bia','Há um destinatário recorrente perto das mensagens. Ainda é associação da investigação.']]},
   {id:'tur-visit',verb:'rastrear',title:'Rastrear presença física',detail:'Procurar nome, data e local em registro independente.',discover:['visitas'],result:[['bia','Uma visita registrada. O nome aproxima os rastros; não explica a função.']]},
   {id:'tur-alias',verb:'verificar',title:'Verificar a identidade do contato',detail:'Cruzar o apelido com registros de proveniências diferentes.',requiresAnyEvidence:['pagamentos','visitas'],result:[['mara','Dá para tratar como o mesmo nó?'],['bia','Com os dois registros, sim. Para dizer o que ele fazia, não.']]},
   {id:'tur-role',verb:'formalizar',title:'Atribuir função de intimidação',detail:'Usar o codinome como prova suficiente do papel no grupo.',fail:true,result:[['mara','Marco como operador de intimidação.'],['bia','Marca como contato associado. O cargo veio do apelido, não do registro.']]},
   {id:'tur-close',verb:'formalizar',title:'Fixar o contato como nó recorrente',detail:'Mesmo contato em mensagens e registros independentes; função permanece alegada.',requiresEvidence:['pagamentos','visitas'],requiresActions:['tur-alias'],complete:true,lead:'turma',conclusion:'SUPPORTED',result:[['bia','Agora o nome aguenta atravessar para a outra linha.']]}
  ],outcome:'Os rastros sustentam recorrência; não sustentam uma biografia criminal.',hints:['Um apelido sozinho não identifica ninguém.','Procure fontes independentes do contato salvo.','Cruze pagamento alegado e presença antes de formalizar.']},
  {id:'meninos',chapter:'CAPÍTULO 6',title:'Os Meninos',date:'MAI 2026 · PERÍCIA',bg:'assets/pf-lab.webp',question:'O que a captura permite afirmar sobre o acesso?',starter:['captura'],objects:[['captura','Captura extraída',50,45]],intro:[['jo','A tela tem uma marca conhecida.'],['mara','E veio de onde?'],['jo','Essa é uma pergunta. “Foi hackeada” é uma resposta sem laudo.']],actions:[
   {id:'men-meta',verb:'verificar',title:'Verificar o arquivo no dispositivo',detail:'Pedir metadados, horário e cadeia de preservação.',discover:['metadata'],recontextualize:['captura'],result:[['jo','O arquivo estava no aparelho nesse horário. O caminho até ele não veio junto.']]},
   {id:'men-system',verb:'verificar',title:'Consultar a instituição citada',detail:'Perguntar se a interface corresponde ao sistema de consulta direta.',discover:['respostaInterpol'],recontextualize:['captura'],result:[['jo','Essa interface não é a consulta direta da Interpol. Pode ser base de outro país usando dados relacionados.']]},
   {id:'men-node',verb:'rastrear',title:'Rastrear contatos ligados ao arquivo',detail:'Procurar se um nó da outra linha reaparece no entorno da extração.',requiresAnyConditions:['lead:turma','evidence:sictag'],result:[['mara','O mesmo contato aparece perto do material.'],['jo','Perto. Não dentro do sistema que você gostaria de nomear.']]},
   {id:'men-hack',verb:'formalizar',title:'Registrar “Interpol invadida”',detail:'Tomar identidade visual e arquivo como prova do sistema de origem.',requiresAnyEvidence:['metadata','respostaInterpol'],fail:true,result:[['mara','Conclusão: houve invasão da Interpol.'],['jo','Não assino. O arquivo existe, a informação se relaciona à base e a interface direta foi descartada. Origem técnica: pendente.']]},
   {id:'men-close',verb:'formalizar',title:'Fixar a conclusão estreita',detail:'Material sugere acesso a informação relacionada; sistema e caminho técnico permanecem pendentes.',requiresEvidence:['metadata','respostaInterpol'],complete:true,lead:'meninos',conclusion:'SUPPORTED',result:[['jo','Isso eu assino.'],['mara','Sem verbo que o laudo não alcança.']]}
  ],outcome:'A precisão exclui a tese mais vistosa e preserva a pergunta técnica correta.',hints:['Imagem mostra conteúdo; metadado situa arquivo. Nenhum nomeia o caminho.','Pergunte à instituição se a interface é realmente dela.','Obtenha metadados e resposta institucional antes de formalizar.']},
  {id:'final',chapter:'FINAL',title:'O relatório vira o caso',date:'15–19 SET 2026',bg:'assets/pf-lab.webp',question:'Como preservar material cujo destino ainda está em disputa?',starter:['pet','drive'],objects:[['pet','Sessão pública',28,37],['drive','Mídia forense',67,57]],intro:[['jo','A cópia terminou. Quase quinhentos gigabytes.'],['lia','Destino?'],['jo','O campo está vazio porque ninguém me deu uma resposta que caiba nele.']],actions:[
   {id:'fin-merit',verb:'verificar',title:'Verificar o resultado da sessão',detail:'Distinguir pedido de vista, questão de ordem e mérito.',result:[['mara','O mérito foi decidido?'],['lia','Não. Houve vista enquanto discutiam a tramitação conjunta.']]},
   {id:'fin-hash',verb:'verificar',title:'Conferir integridade da cópia',detail:'Validar mídia, registro técnico e lacre.',result:[['jo','Cópia íntegra. Lacre pronto. Destino ainda em branco.']]},
   {id:'fin-destination',verb:'formalizar',title:'Preencher o destino por inferência',detail:'Escolher um gabinete antes de definição institucional.',fail:true,result:[['mara','Se eu preencher pelo último pedido...'],['lia','Você transforma hipótese processual em cadeia de custódia. Deixa em branco.']]},
   {id:'fin-seal',verb:'formalizar',title:'Lacrar com destino pendente',detail:'Preservar integridade, registrar auxílio técnico e manter a destinação sem resposta.',requiresActions:['fin-merit','fin-hash'],complete:true,end:true,conclusion:'PENDING',result:[]}
  ],outcome:'A mídia fica preservada. O procedimento continua aberto.',hints:['O pedido de vista não decidiu o mérito.','Integridade e destino são perguntas diferentes.','Confira sessão e cópia; preserve o campo sem resposta.']}
 ]
};
})();
